Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -22,14 +22,21 @@ jobs:
     - name: Build
       run: dotnet build --no-restore -c Release
     - name: Test
-      run: dotnet test --logger trx --results-directory "TestResults-StratusCube.Extensions.Configuration.RavenDB"
+      run: dotnet test --logger trx --results-directory "TestResults"
     - name: Upload dotnet test results
       uses: actions/upload-artifact@v3
       with:
-        name: dotnet-results-StratusCube.Extensions.Configuration.RavenDB
-        path: TestResults-StratusCube.Extensions.Configuration.RavenDB
+        name: dotnet-results
+        path: TestResults
       # Use always() to always run this step to publish test results when there are test failures
       if: ${{ always() }}
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Test Results           # Name of the check run which will be created
+        path: TestResults/*.trx    # Path to test results
+        reporter: dotnet-trx       # Format of test results
     - name: Pack
       run: dotnet pack -c Release
     - name: Upload a Build Artifact
@@ -54,7 +61,7 @@ jobs:
         path: ./artifacts
     - name: publish
       working-directory: ./artifacts
-      run: dotnet nuget push ./artifacts/**/*.nupkg
+      run: dotnet nuget push **/*.nupkg
         --source https://api.nuget.org/v3/index.json
         --skip-duplicate --no-symbols
         -k ${NUGET_KEY}
